version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: jwt-playground-db
    restart: always
    environment:
      MYSQL_DATABASE: 'jwt-playground'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3309:3306'
    volumes:
      - jwt-playground-db:/var/lib/mysql
# Names our volume
volumes:
  jwt-playground-db:
